# Generated by Django 5.1.5 on 2025-02-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kakao_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kakaoplace",
            name="rating_count",
            field=models.IntegerField(default=0),
        ),
    ]
