# Generated by Django 5.1.5 on 2025-02-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kakao_api", "0002_kakaoplace_rating_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="kakaoplace",
            name="review_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
