# Generated by Django 5.1.5 on 2025-02-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakao_api', '0004_kakaoplace_review_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kakaoplace',
            name='review_summary',
        ),
    ]
