# Generated by Django 5.1.5 on 2025-02-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakao_api', '0005_remove_kakaoplace_review_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakaoplace',
            name='review_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
